# Generated by Django 5.1.6 on 2025-03-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='Recipe',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ledger.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ledger.recipe'),
        ),
    ]
